#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module RailsPipeline
  # forward declarations
  class EncryptedMessage < ::ProtocolBuffers::Message; end

  class EncryptedMessage < ::ProtocolBuffers::Message
    # forward declarations

    # enums
    module EventType
      include ::ProtocolBuffers::Enum

      set_fully_qualified_name "RailsPipeline.EncryptedMessage.EventType"

      CREATED = 0
      UPDATED = 1
      DELETED = 2
    end

    set_fully_qualified_name "RailsPipeline.EncryptedMessage"

    required :string, :uuid, 1
    required :string, :salt, 2
    required :string, :iv, 3
    required :string, :ciphertext, 4
    optional :string, :owner_info, 5
    optional :string, :type_info, 6
    optional :string, :topic, 7
    optional ::RailsPipeline::EncryptedMessage::EventType, :event_type, 8, :default => ::RailsPipeline::EncryptedMessage::EventType::CREATED
    required :string, :api_key, 9
  end

end
