#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module RailsPipeline
  # forward declarations
  class EncryptedMessage < ::ProtocolBuffers::Message; end

  class EncryptedMessage < ::ProtocolBuffers::Message
    set_fully_qualified_name "RailsPipeline.EncryptedMessage"

    required :string, :uuid, 1
    required :string, :salt, 2
    required :string, :iv, 3
    required :string, :ciphertext, 4
    optional :string, :owner_info, 5
    optional :string, :type_info, 6
  end

end
