#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

# forward declarations
class DefaultEmitter_1_0 < ::ProtocolBuffers::Message; end

class DefaultEmitter_1_0 < ::ProtocolBuffers::Message
  set_fully_qualified_name "DefaultEmitter__1__0"

  required :int32, :id, 1
  required :string, :foo, 2
end

