#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

# forward declarations
class TestEmitter_1_1 < ::ProtocolBuffers::Message; end

class TestEmitter_1_1 < ::ProtocolBuffers::Message
  set_fully_qualified_name "TestEmitter__1__1"

  required :int32, :id, 1
  required :string, :foo, 2
  optional :string, :extrah, 3
end

